<script lang="ts">
 import {untrack} from 'svelte';
 import {bytes,type AppDocument,type AppRecord,type Asset,type RecordValue} from './application';
 type Api = <T>(path:string,method?:string,body?:unknown,key?:string)=>Promise<T>;
 let {app,api,onerror,upload,download}:{app:AppDocument;api:Api;onerror:(message:string)=>void;upload:(file:File)=>Promise<Asset>;download:(file:Asset)=>Promise<void>}=$props();
 let pageKey=$state(untrack(()=>app.ui.pages[0]?.key ?? '')),filesView=$state(false),records=$state<AppRecord[]>([]),files=$state<Asset[]>([]),references=$state<Record<string,AppRecord[]>>({}),nextCursor=$state<string|null>(null);
 let draft=$state<Record<string,RecordValue>>({}),editing=$state<AppRecord|null>(null),busy=$state(false),selected=$state(''),actionResult=$state('');
 let page=$derived(app.ui.pages.find(p=>p.key===pageKey));
 let dataGeneration=0;
 let pendingCreate:{fingerprint:string;key:string}|null=null;
 async function load(reset=true){const generation=++dataGeneration;if(!page)return;try{const result=await api<{items:AppRecord[];next_cursor:string|null}>(`apps/${app.id}/records/${page.entity.key}${!reset&&nextCursor?`?after=${nextCursor}`:''}`);const assets=await api<Asset[]>(`apps/${app.id}/files`);if(generation!==dataGeneration)return;records=reset?result.items:[...records,...result.items];files=assets;nextCursor=result.next_cursor;
 const targets=[...new Set(page.entity.fields.filter(f=>f.type==='reference').map(f=>f.entity!))];const refs:Record<string,AppRecord[]>={};for(const target of targets){let cursor:string|null=null;let list:AppRecord[]=[];do{const r=await api<{items:AppRecord[];next_cursor:string|null}>(`apps/${app.id}/records/${target}${cursor?`?after=${cursor}`:''}`);list=[...list,...r.items];cursor=r.next_cursor;}while(cursor&&list.length<10000);refs[target]=list;}if(generation===dataGeneration)references=refs;
 }catch(e){onerror(e instanceof Error?e.message:'Could not load application data.');}}
 $effect(()=>{const identity=app.id;const key=pageKey;if(identity&&key)untrack(()=>{void load();draft={};editing=null;selected='';});});
 async function task(fn:()=>Promise<void>){if(busy)return;busy=true;try{await fn();}catch(e){onerror(e instanceof Error?e.message:'Operation failed.');}finally{busy=false;}}
 function setField(key:string,value:RecordValue){draft={...draft,[key]:value};}
 function edit(record:AppRecord){editing=record;draft={...record.data};selected=record.id;}
 function save(){void task(async()=>{if(!page)return;const values={...draft};for(const field of page.entity.fields)if(field.type==='boolean'&&values[field.key]===undefined)values[field.key]=false;const body={app_version:app.version,data:values,...(editing?{version:editing.version}:{})};const fingerprint=JSON.stringify({app:app.id,entity:page.entity.key,body});if(!editing&&pendingCreate?.fingerprint!==fingerprint)pendingCreate={fingerprint,key:crypto.randomUUID()};await api(`apps/${app.id}/records/${page.entity.key}${editing?`/${editing.id}`:''}`,editing?'PATCH':'POST',body,editing?undefined:pendingCreate!.key);pendingCreate=null;draft={};editing=null;await load();});}
 function archive(record:AppRecord){if(!confirm('Archive this record? Referenced records cannot be archived.'))return;void task(async()=>{if(!page)return;await api(`apps/${app.id}/records/${page.entity.key}/${record.id}/archive`,'POST',{version:record.version});if(editing?.id===record.id){editing=null;draft={};}await load();});}
 function execute(key:string){void task(async()=>{const record=records.find(r=>r.id===selected);if(!record)throw Error('Select a record first.');const result=await api<{result:unknown}>(`apps/${app.id}/actions/${key}`,'POST',{app_version:app.version,record_id:record.id,record_version:record.version});actionResult=JSON.stringify(result.result,null,2);});}
 function fileInput(event:Event){const target=event.currentTarget as HTMLInputElement;const file=target.files?.[0];if(file)void task(async()=>{await upload(file);files=await api<Asset[]>(`apps/${app.id}/files`);target.value='';});}
 function valueLabel(value:RecordValue|undefined){return value===undefined||value===null?'—':typeof value==='boolean'?(value?'Yes':'No'):String(value);}
 function recordLabel(record:AppRecord){const first=Object.values(record.data).find(v=>typeof v==='string'&&v);return first?String(first):record.id;}
</script>
<nav class="app-pages" aria-label="Application pages">{#each app.ui.pages as p}<button class:active={!filesView&&pageKey===p.key} onclick={()=>{pageKey=p.key;filesView=false;}}>{p.title}</button>{/each}<button class:active={filesView} onclick={()=>filesView=true}>Files & storage</button></nav>
{#if filesView}
<section class="panel"><div class="split-heading"><div><h2>Files & storage</h2><p>Private application files. Compression is lossless and used only when it saves space.</p></div><label class="file-upload">Upload file<input type="file" onchange={fileInput} disabled={busy}/></label></div>
<div class="storage-stats"><span>{files.length} files</span><span>{bytes(files.reduce((n,f)=>n+f.original_size,0))} original</span><span>{bytes([...new Map(files.map(f=>[f.sha256,f])).values()].reduce((n,f)=>n+f.stored_size,0))} unique stored bytes</span></div>
<div class="table-scroll"><table><thead><tr><th>File</th><th>Original</th><th>Stored object</th><th>Codec</th><th></th></tr></thead><tbody>{#each files as file}<tr><td>{file.filename}<small>{file.sha256.slice(0,16)}…</small></td><td>{bytes(file.original_size)}</td><td>{bytes(file.stored_size)}</td><td>{file.codec}</td><td><button onclick={()=>void task(()=>download(file))} disabled={busy}>Download</button></td></tr>{/each}</tbody></table></div>
{#if !files.length}<p class="empty">No files yet. Uploads use the same storage pipeline for every application.</p>{/if}<p class="notice">8 MiB per file · 128 MiB logical quota per app · stored bytes deduplicated within this app. Files are delivered as downloads, not executable content.</p></section>
{:else if page}
<div class="workspace-columns"><section class="panel"><div class="split-heading"><div><h2>{page.title}</h2><p>{records.length} loaded records{nextCursor?' · more available':''}</p></div><button class="secondary" onclick={()=>void load()} disabled={busy}>Refresh</button></div>
<div class="table-scroll"><table><thead><tr><th>Select</th>{#each page.entity.fields as field}<th>{field.label}</th>{/each}<th></th></tr></thead><tbody>{#each records as record}<tr class:selected={selected===record.id}><td><input type="radio" name="selected-record" aria-label={`Select ${recordLabel(record)}`} checked={selected===record.id} onchange={()=>selected=record.id}/></td>{#each page.entity.fields as field}<td>{#if field.type==='file'&&record.data[field.key]}{files.find(f=>f.id===record.data[field.key])?.filename ?? 'Attached file'}{:else if field.type==='reference'&&record.data[field.key]}{recordLabel(references[field.entity!]?.find(r=>r.id===record.data[field.key]) ?? {id:String(record.data[field.key]),version:1,data:{}})}{:else}{valueLabel(record.data[field.key])}{/if}</td>{/each}<td>{#if page.can_write}<button onclick={()=>edit(record)} disabled={busy}>Edit</button><button class="quiet" onclick={()=>archive(record)} disabled={busy}>Archive</button>{/if}</td></tr>{/each}</tbody></table></div>
{#if !records.length}<p class="empty">No records yet. This collection is persisted in the database, not in browser storage.</p>{/if}{#if nextCursor}<button class="secondary" onclick={()=>void load(false)} disabled={busy}>Load more</button>{/if}
{#if page.actions.length}<section class="capabilities"><h3>Capabilities</h3>{#each page.actions as action}<div class="capability"><div><strong>{action.label}</strong><small>{action.capability} · v{action.version}</small></div>{#if action.resolution?.available}<button class="primary" onclick={()=>execute(action.key)} disabled={busy||!selected}>Run</button>{:else}<span class="missing">Not installed</span>{/if}</div>{#if !action.resolution?.available}<p class="notice">Only this action is unavailable. Its input port, page, records, and files remain intact.</p>{/if}{/each}</section>{/if}
{#if actionResult}<pre class="result">{actionResult}</pre>{/if}
</section>
{#if page.can_write}<form class="panel record-form" onsubmit={e=>{e.preventDefault();save();}}><div class="split-heading"><h2>{editing?'Edit record':'New record'}</h2>{#if editing}<button type="button" class="quiet" onclick={()=>{editing=null;draft={};}}>Cancel</button>{/if}</div>
{#each page.entity.fields as field}
<label>{field.label}{field.required?' *':''}
{#if field.type==='boolean'}<input type="checkbox" checked={draft[field.key]===true} onchange={e=>setField(field.key,e.currentTarget.checked)}/>
{:else if field.type==='multiline'}<textarea rows="4" value={String(draft[field.key]??'')} required={field.required} oninput={e=>setField(field.key,e.currentTarget.value)}></textarea>
{:else if field.type==='select'}<select value={String(draft[field.key]??'')} required={field.required} onchange={e=>setField(field.key,e.currentTarget.value||null)}><option value="">Choose…</option>{#each field.options??[] as option}<option value={option}>{option}</option>{/each}</select>
{:else if field.type==='file'}<select value={String(draft[field.key]??'')} required={field.required} onchange={e=>setField(field.key,e.currentTarget.value||null)}><option value="">Choose a stored file…</option>{#each files as file}<option value={file.id}>{file.filename}</option>{/each}</select>
{:else if field.type==='reference'}<select value={String(draft[field.key]??'')} required={field.required} onchange={e=>setField(field.key,e.currentTarget.value||null)}><option value="">Choose a record…</option>{#each references[field.entity!]??[] as record}<option value={record.id}>{recordLabel(record)}</option>{/each}</select>
{:else}<input type={field.type==='integer'?'number':field.type==='date'?'date':'text'} step={field.type==='integer'?'1':undefined} value={String(draft[field.key]??'')} required={field.required} oninput={e=>setField(field.key,e.currentTarget.value===''?null:field.type==='integer'?Number(e.currentTarget.value):e.currentTarget.value)}/>{/if}
</label>{/each}<button class="primary" type="submit" disabled={busy}>{busy?'Saving…':editing?'Save changes':'Create record'}</button><small>Application v{app.version}{editing?` · record v${editing.version}`:''}. Conflicting edits are rejected rather than silently overwritten.</small></form>{/if}
</div>
{/if}
